spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/toycollect
    username: root
    password: TriKhai2004@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    format-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: "trikhaikhmt@gmail.com"
    password: "bppv ywmd guha vfrr"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secretKey: ih67YD1YLVcK0rp95jchoOuw7hGgmH/NR7EC4yOfUI0=

fileUpload:
  rootPath: D:\C치c file kh치c\SpringBoot\toycollect\src\main\resources\static\uploads
#  avatar:
#    rootPath:
#  product:
#    rootPath: D:\C치c file kh치c\SpringBoot\toycollect\src\main\resources\static\uploads\products